apiVersion: v1
kind: Service
metadata:
  name: myapi-service
spec:
  selector:
    app: myapi
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      nodeport: 30000
  type: LoadBalancer
