apiVersion: v1
kind: Service
metadata:
  name: myapi-service
spec:
  selector:
    app: myapi
  ports:
    - protocol: TCP
      port: 443
      targetPort: 443
      nodePort: 30000    # Specify a static port for NodePort
  type: LoadBalancer        # Change the service type to NodePort